APP_NAME = "BiodataParser"
APP_VERSION = "0.1.0"

REVIEW_STATUS_PARSED = "Parsed"
REVIEW_STATUS_NEEDS_REVIEW = "Needs Review"
REVIEW_STATUS_REVIEWED = "Reviewed"
REVIEW_STATUS_FAILED = "Failed"

DEFAULT_MIN_TEXT_LENGTH = 40
